name: Deploy App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Clean install (fix rollup issue)
      run: |
        rm -rf node_modules
        rm -f package-lock.json
        npm install
      
    - name: Build
      run: npm run build
      
    - name: Configure GitHub Pages
      run: |
        # Create a CNAME file if you have a custom domain
        # echo "your-custom-domain.com" > ./dist/CNAME
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
        clean: true
